on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Compile Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - name: Compile Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "mat-1"
          user-email: "github@matdoes.dev"
          message: "Compiled TS into JS"
  automerge:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
